### ISSUE TITLE
Can't make it work after update

### ISSUE THREAD

**Issue by Maetzi87** [rbogdanov/lovelace-animated-background#14]
Hi,
maybe I'm missing something but I can't figure out how to make animated background work again after last core update...
The pictures simply don't show up. After clearing cache, the background is showing, but the cards are gone. After refresh, cards are here, background is white. Turning on/off Kiosk-mode doesn't change a thing. Issue appearing on a Fire 10 Tablet, my mobile phone (Z Fold 4) and in my Browser.

Homeassistant-Version: 

![Image](https://github.com/user-attachments/assets/1cd01a35-ae9d-4f8f-a509-096c32065f56)

Dashboard-config:
```
kiosk_mode:
  entity_settings:
    - entity:
        input_boolean.kioskmode: 'on'
      hide_sidebar: true
      hide_header: true
animated_background:
  default_url: /local/lovelace/a_background/sunny_1.mp4
  transparent_panel: false
  opacity: 0
  groups:
    - name: weather
      config:
        entity: sensor.weather_day_night
        state_url:
          sunny-day-on:
            - /local/lovelace/a_background/sunny_1.mp4
            - /local/lovelace/a_background/sunny_2.mp4
            - /local/lovelace/a_background/sunny_3.mp4
            - /local/lovelace/a_background/sunny_4.mp4
            - /local/lovelace/a_background/sunny_5.mp4
            - /local/lovelace/a_background/sunny_6.mp4
            - /local/lovelace/a_background/sunny_7.mp4
          partlycloudy-day-on:
            - /local/lovelace/a_background/partlycloudy_1.mp4
            - /local/lovelace/a_background/partlycloudy_2.mp4
            - /local/lovelace/a_background/partlycloudy_3.mp4
            - /local/lovelace/a_background/partlycloudy_4.mp4
          cloudy-day-on:
            - /local/lovelace/a_background/cloudy_1.mp4
            - /local/lovelace/a_background/cloudy_2.mp4
            - /local/lovelace/a_background/cloudy_3.mp4
            - /local/lovelace/a_background/cloudy_4.mp4
          mostlycloudy-day-on:
            - /local/lovelace/a_background/mostlycloudy_1.mp4
            - /local/lovelace/a_background/cloudy_1.mp4
            - /local/lovelace/a_background/cloudy_2.mp4
          clear-night-day-on:
            - /local/lovelace/a_background/night_1.mp4
            - /local/lovelace/a_background/night_2.mp4
            - /local/lovelace/a_background/night_3.mp4
            - /local/lovelace/a_background/night_4.mp4
          fog-day-on:
            - /local/lovelace/a_background/foggy_1.mp4
            - /local/lovelace/a_background/foggy_2.mp4
            - /local/lovelace/a_background/foggy_3.mp4
            - /local/lovelace/a_background/foggy_4.mp4
          rainy-day-on:
            - /local/lovelace/a_background/rain_1.mp4
            - /local/lovelace/a_background/rain_2.mp4
            - /local/lovelace/a_background/rain_3.mp4
            - /local/lovelace/a_background/rain_4.mp4
          pouring-day-on:
            - /local/lovelace/a_background/pouring_1.mp4
            - /local/lovelace/a_background/pouring_2.mp4
            - /local/lovelace/a_background/pouring_3.mp4
          lightning-rainy-day-on:
            - /local/lovelace/a_background/thunder_1.mp4
            - /local/lovelace/a_background/thunder_2.mp4
            - /local/lovelace/a_background/thunder_3.mp4
            - /local/lovelace/a_background/thunder_4.mp4
          snowy-day-on:
            - /local/lovelace/a_background/snow_1.mp4
            - /local/lovelace/a_background/snow_2.mp4
            - /local/lovelace/a_background/snow_3.mp4
            - /local/lovelace/a_background/snow_4.mp4
          snowy-rainy-day-on:
            - /local/lovelace/a_background/snowy_rainy.mp4
          sunny-night-on:
            - /local/lovelace/a_background/night_1.mp4
            - /local/lovelace/a_background/night_2.mp4
            - /local/lovelace/a_background/night_3.mp4
            - /local/lovelace/a_background/night_4.mp4
          partlycloudy-night-on:
            - /local/lovelace/a_background/night/partlycloudy-night_1.mp4
            - /local/lovelace/a_background/night/partlycloudy-night_2.mp4
          cloudy-night-on:
            - /local/lovelace/a_background/night/cloudy-night_1.mp4
            - /local/lovelace/a_background/night/cloudy-night_2.mp4
          mostlycloudy-night-on:
            - /local/lovelace/a_background/night/mostlycloudy-night_1.mp4
          clear-night-night-on:
            - /local/lovelace/a_background/night_1.mp4
            - /local/lovelace/a_background/night_2.mp4
            - /local/lovelace/a_background/night_3.mp4
            - /local/lovelace/a_background/night_4.mp4
          fog-night-on:
            - /local/lovelace/a_background/night/foggy-night.mp4
          rainy-night-on:
            - /local/lovelace/a_background/night/rain-night_1.mp4
            - /local/lovelace/a_background/night/rain-night_2.mp4
            - /local/lovelace/a_background/night/rain-night_3.mp4
          pouring-night-on:
            - /local/lovelace/a_background/night/pouring-night_1.mp4
            - /local/lovelace/a_background/night/pouring-night_2.mp4
          lightning-rainy-night-on:
            - /local/lovelace/a_background/night/lightning-night_1.mp4
            - /local/lovelace/a_background/night/lightning-night_2.mp4
            - /local/lovelace/a_background/night/lightning-night_3.mp4
          snowy-night-on:
            - /local/lovelace/a_background/night/snow-night_1.mp4
            - /local/lovelace/a_background/night/snow-night_1.mp4
          snowy-rainy-night-on:
            - /local/lovelace/a_background/night/snow-rain-night.mp4
          sunny-day-off:
            - /local/lovelace/a_background/png/sunny.png
          partlycloudy-day-off:
            - /local/lovelace/a_background/png/partlycloudy.png
          cloudy-day-off:
            - /local/lovelace/a_background/png/cloudy.png
          mostlycloudy-day-off:
            - /local/lovelace/a_background/png/mostlycloudy.png
          clear-night-day-off:
            - /local/lovelace/a_background/png/night.png
          fog-day-off:
            - /local/lovelace/a_background/png/foggy.png
          rainy-day-off:
            - /local/lovelace/a_background/png/rain.png
          pouring-day-off:
            - /local/lovelace/a_background/png/pouring.png
          lightning-rainy-day-off:
            - /local/lovelace/a_background/png/thunder.png
          snowy-day-off:
            - /local/lovelace/a_background/png/snow.png
          snowy-rainy-day-off:
            - /local/lovelace/a_background/png/snowy-rainy.png
          sunny-night-off:
            - /local/lovelace/a_background/png/night.png
          partlycloudy-night-off:
            - /local/lovelace/a_background/png/partlycloudy-night.png
          cloudy-night-off:
            - /local/lovelace/a_background/png/cloudy-night.png
          mostlycloudy-night-off:
            - /local/lovelace/a_background/png/mostlycloudy-night.png
          clear-night-night-off:
            - /local/lovelace/a_background/png/night.png
          fog-night-off:
            - /local/lovelace/a_background/png/foggy-night.png
          rainy-night-off:
            - /local/lovelace/a_background/png/rain-night.png
          pouring-night-off:
            - /local/lovelace/a_background/png/pouring-night.png
          lightning-rainy-night-off:
            - /local/lovelace/a_background/png/thunder-night.png
          snowy-night-off:
            - /local/lovelace/a_background/png/snow-night.png
          snowy-rainy-night-off:
            - /local/lovelace/a_background/png/snow-rain-night.png
views:
  - theme: default
    animated_background: weather
    icon: mdi:home
    layout:
      width: 700
      columns: 1
    type: custom:masonry-layout
    path: home
    badges: []
    cards:
    ...
```

Please help!
